name: CI Lint

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  js-ts:
    name: ESLint & Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm ci || npm i --no-audit --no-fund
      - run: npx eslint . || true
      - run: npx prettier -c "**/*" || true
      - run: npm run lint:js

  css:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm ci || npm i --no-audit --no-fund
      - run: npx stylelint "**/*.{css,scss}" || true
      - run: npm run lint:css

  markdown-json-yaml-shell:
    name: MD / Spectral / ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - run: npm i -g markdownlint-cli @stoplight/spectral-cli shellcheck || true
      - run: markdownlint "**/*.md" || true
      - run: spectral lint "**/*.{json,yaml,yml}" -r .spectral.yaml || true
      - name: ShellCheck
        run: |
          shopt -s globstar || true
          shellcheck **/*.sh || true

  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-php@v4.6.2
          with:
            php-version: '8.2'
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            standard: 'WordPress' # Standard to use. Accepts WordPress|WordPress-Core|WordPress-Docs|WordPress-Extra|WordPress-VIP-Go|WordPressVIPMinimum|10up-Default.
            extra_args: '--report-json=./phpcs.json'
        - name: Update summary
          run: |
            npm i -g github:10up/phpcs-json-to-md
            phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
            cat phpcs.md >> $GITHUB_STEP_SUMMARY
          if: always()
